services:
  - type: web
    name: michaelsdiscovery
    runtime: python
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
